#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
manage_etc_hosts: false

packages:
  - nano
  - wget
  - curl
  - zip
  - unzip
  - git
  - python3
  - python3-pip
